spring.application.name=petshop-api

# Banco de dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/petshop}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Servidor
server.port=8080

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItcGV0c2hvcC1hcGktand0}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logs
logging.level.com.petshop=DEBUG
